openapi: "3.0.2"
info:
  title: DRAFT Fjord Control API - Analytics/GetDecimatedTimeseries
  version: '1.3'
  description: Endpoint for retireving downsampled timeseries data within a period of time 
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/TTH_1/DecimatedTimeSeries/1.3
  - url: https://api.fjordcontrol.no/v2
paths:
  /Analytics/GetDecimatedTimeseries:
    post:
      summary: Get decimated data points.
      description: >
        Get an array of decimated and sorted data points given temporal constraints and a decimation policy.
      requestBody:
        description: >
          The purpose of this API is to provide timeseries data suitable for displaying as graphs.

          Given a pixelspace on the user device
          the frontend developers must be able to ask for a decimated (or downsampled) set of data points
          with the purpose of renderering a timesires graph that makes good use of the available pixel space.

          The service providing the decimated data may adjust the request parameters for computational preferences.
          Repetitive requests with the same request parameters must yield the same result.
          Results must not be biased to any given time zone.
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DecimatedTimeseriesFilter'
      responses:
        200:
          description: OK - Request fullfilled and decimated timeseries is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecimatedTimeseries'
        403: 
          description: Forbidden - Bearer token not approved (TODO - Is this true? Check with FC.)
        422: 
          description: >
            Unprocessable Entity - Failed to process at least one of the timeseries filters.
            Returns a text string that hints to the problem.
        500:
          description: Internal Server Error - Returns a text string that hints to problem
components:
  schemas:
    Timestamp:
      description: Timestamp associated with some event or data point
      type: string
      format: ISO 8601 UTC
    Value:
      description: >
        Representes some measured value or perhaps some computed data point.
        The float value must be encoded according to the semantics of the timeseries.
         * 'bool' - represented by 0 and 1 with or without decimal '.0'.
         * 'int' - represented without decimals or with decimal '.0'.
         * 'float' - represented with or without decimals.   
      type: number
      format: float
    TimestampedValues:
      description: >
        Contains measurement values sorted by timestamps.
        Measurements are represented by a Timestamps array and a Values array, both that are of equal length.
      type: object
      properties:
        ActualCount:
          description: >
            1. The ActualCount is the number of data points that are returned. 
            2. The length of the Timestamps array and the Values array must both be of this length.
            3. Data points consist of
               - Data extracted from the time slots by applying the decimation policy.
               - An additional leading data point, the last before the time window, if it exists.
          type: number
          format: int
        Timestamps:
          type: array
          items:
            $ref: '#/components/schemas/Timestamp'
        Values:
          type: array
          items:
            $ref: '#/components/schemas/Value'
      required:
      - ActualCount
      - Timestamps
      - Values            
    DecimatedTimeseries:
      description: Contains the result of the decimation process.
      type: object
      properties:
        Constraints:
          allOf:
          - description: >
              Contains the decimation constraints that were actually used to compute the decimated timeseries.
              These constraints are normally a copy of the constraints given in DecimatedTimeseriesFilter but
              may have been adjusted for computational preferences. 
          - $ref: '#/components/schemas/TemporalConstraints'
        Selectors:
          description: Array of timeseries selectors identifying the decimated timeseries 
          type: array
          items:
            $ref: '#/components/schemas/TimeseriesSelector'
        Results:
          description: >
            Decimated timeseries computed from associated decimation constrains.
            It sorted in same order as the timeseries selectors
          type: array
          items:
            $ref: '#/components/schemas/TimestampedValues'  
      required:
      - Constraints
      - Selectors
      - Results         
    DecimatedTimeseriesFilter:
      description: Filter specification for decimated timeseries 
      type: object
      properties:
        Constraints:
          $ref: '#/components/schemas/TemporalConstraints'
        Selectors:
          description: Array of timeseries selectors
          type: array
          items:
            $ref: '#/components/schemas/TimeseriesSelector'
      required:
      - Constraints
      - Selectors
    TemporalConstraints:
      description: >
        Temporal constraints for decimated timeseries.
        The constraints are defined in terms of a time window and a number of time slots.
        The window size is defined as the difference between DateFrom and DateTo.
        The slot size is defined as the quotient from dividing the window size by the slot count.
        The decimation algorithm may snap window and slots to some temporal alignment for computational preferences.
        The snap must not be larger then half a time slot.
        The snap must not result in more than requested slot count to be created.
        The snap may result in a slight reduction in the slot count.
      type: object
      properties:
        DateFrom:
          description: >
            Inclusive (>=) start time of requested timeseries.
            The decimation algorithm may snap the DateFrom time to some temporal alignment for computational preferences.
          type: string
          format: ISO 8601 UTC
        DateTo:
          description: >
            Inclusive (<=) end time of requested timeseries
            The decimation algorithm may snap the DateTo time to some temporal alignment for computational preferences.
            The snap must not be an earlier time than the original DateTo value.
          type: string
          format: ISO 8601 UTC
        SlotCount:
          description: >
            The number of time slots to divide timeseries into.
            Usually corresponds to max number of data points to return although
            this depends on the decimation policy.
            E.g; `extr` policy returns two values per slot if those exists.
            The decimation algorithm may slightly reduce the slot count for computational preferences.
          type: number
        SortOrder:
          description: >
            How to sort the decimated timeseries
             * `0: asc` - Sort by ascending timestamp
             * `1: desc` - Sort by descending timestamp
          type: number
      required:
      - DateFrom
      - DateTo
      - SlotCount
      - SortOrder
    DeviceType:
      description: >
        Byte enumeration identifying device type. 
         * `0: Battery`
         * `1: Engine`
         * `2: Pms`
         * `3: DoorSwitch`
         * `4: Generator`
         * `5: GeneratorControl`
         * `6: Mains`
         * `7: RoomSensor`
         * `8: Transformer`
         * `9: Vessel`
         * `10: CoolingSystem`
         * `11: Propulsion`
         * `12: Charger`
         * `13: DcDc`
         * `15: Sterndrive`
         * `16: Manouver`
         * `17: Busbar`
      type: number
      format: byte
    TimeseriesSelector:
      description: Specification identifying a single timeserie 
      type: object
      properties:
        DeviceId:
          description: Short int identifying real world device of given "DeviceType"
          type: number
          format: short
        DeviceType:
          $ref: '#/components/schemas/DeviceType'
        MeasurementId:
          description: Identifier of measurement.
          type: number
        DecimationPolicy:
          description: >
            1. How to sample measurements for each time slot:
             * No value is selected if no value exists within the time slot
             * `0: min` - Select minimum value within time slot.
             * `1: max` - Select maximum value within time slot.
             * `2: mean` - Calculate mean value within time slot. Returns averaged timestamp for values in mean.
             * `3: extr` - Select both minimum and maximum (extremals) within each time slot, if they exist. 
             * `4: meanL` - Select both mean value and (L)ast value within each timeslot, if they exist. Mean value excludes the last point seen in the time slot. Returns averaged timestamp for values in mean and exact timestamp for last value.
             2. In addition to data decimated from time slots, 
             select a "leading" data point which is the last data point before the time window.
             3. When the data stream is sparse, 
             leading data point might not exist or there might be time slots without data.
             That is ok. The output of the decimation algorithm should be reduced accordingly.
          type: number
          format: int
      required:
      - DeviceId
      - DeviceType
      - MeasurementId
      - DecimationPolicy